language: r
cache: packages

os: 
  - osx
    env: EXTRA_BUILD_FLAGS="-DSTIR_OPENMP:BOOL=OFF" CC=gcc CXX=g++
  - linux

r_github_packages:
  - jimhester/lintr
  - jimhester/covr
#  - MangoTheCat/goodpractice

after_success:
  - Rscript -e 'lintr::lint_package()'
#  - Rscript -e 'library(goodpractice); gp()'  #commented for faster Travis support, main issues are resolved
  - travis_wait 40 Rscript -e "covr::codecov()"; # this takes too long
