language: r
cache: packages
warnings_are_errors: false

r_github_packages:
  - jimhester/lintr
  - jimhester/covr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'library(covr); codecov()'
