language: r
cache: packages

os: 
  - osx
  - linux

r_github_packages:
  - jimhester/lintr
  - jimhester/covr
#  - MangoTheCat/goodpractice

after_success:
  - Rscript -e 'lintr::lint_package()'
#  - Rscript -e 'library(goodpractice); gp()'  #commented for faster Travis support, main issues are resolved
#  - Rscript -e 'library(covr); codecov()'
