# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim_fin_chrom <- function(pop_size, init_heterozygosity, run_time, size_in_Morgan, seed, R) {
    .Call('_junctions_sim_fin_chrom', PACKAGE = 'junctions', pop_size, init_heterozygosity, run_time, size_in_Morgan, seed, R)
}

sim_inf_chrom <- function(pop_size, init_heterozygosity, run_time, size_in_Morgan, markers, seed) {
    .Call('_junctions_sim_inf_chrom', PACKAGE = 'junctions', pop_size, init_heterozygosity, run_time, size_in_Morgan, markers, seed)
}

